🔧  [S3] S3: 환경 설정
TeamAvAb/AvAb-Back pull request #10
Opened 2024-01-12 06:42 UTC by jinuklee777

## 📍 PR 타입 (하나 이상 선택)
- [ ] 기능 추가
- [ ] 버그 수정
- [x] 의존성, 환경 변수, 빌드 관련 코드 업데이트
- [ ] 기타 사소한 수정

## ❗️ 관련 이슈 링크
Close #9 

## 📌 개요
- S3 설정

## 🔁 변경 사항
- AmazonS3Manager, AmazonConfig 추가
- ErrorStatus에 S3 관련 에러 추가

## 📸 스크린샷

## 👀 기타 더 이야기해볼 점

## ✅ 체크 리스트
- [x] PR 템플릿에 맞추어 작성했어요.
- [x] 변경 내용에 대한 테스트를 진행했어요.
- [x] 프로그램이 정상적으로 동작해요.
- [x] PR에 적절한 라벨을 선택했어요.
- [x] 불필요한 코드는 삭제했어요.

2024-01-12 07:00 UTC, 88dldl commented
확인했습니다! 👍

2024-01-15 08:09 UTC, eomgerm requested changes

2024-01-15 09:39 UTC, eomgerm requested changes

2024-01-15 09:39 UTC, eomgerm commented on src/main/java/com/avab/avab/apiPayload/exception/S3/S3ObjectException.java
> +    public S3ObjectException(BaseErrorCode code) {
그냥 S3Exception 하나로 퉁 치시죠!

2024-01-15 09:40 UTC, jinuklee777 commented on src/main/java/com/avab/avab/apiPayload/exception/S3/S3ObjectException.java
> +    public S3ObjectException(BaseErrorCode code) {
넵!

2024-01-15 09:52 UTC, eomgerm approved these changes
굿 머지하시죠!

2024-01-15 09:58 UTC, merged