✨ [Feat] 플로우 생성시 추천 플로우 API 구현
TeamAvAb/AvAb-Back pull request #113
Opened 2024-02-13 07:56 UTC by 88dldl

## 📍 PR 타입 (하나 이상 선택)
- [x] 기능 추가
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트
- [ ] 기타 사소한 수정

## ❗️ 관련 이슈 링크
Close #112

## 📌 개요
- 플로우 생성시 추천플로우 api 구현

## 🔁 변경 사항
1. 플로우 생성시 추천플로우 api 구현 했습니다 25024299b73b18bfdebae3161f952e2b538e77fc
=> 제이미님이 구현하신 추천 레크레이션 로직 참고했습니다

## 📸 스크린샷

## 👀 기타 더 이야기해볼 점

## ✅ 체크 리스트
- [x] PR 템플릿에 맞추어 작성했어요.
- [x] 변경 내용에 대한 테스트를 진행했어요.
- [x] 프로그램이 정상적으로 동작해요.
- [x] PR에 적절한 라벨을 선택했어요.
- [x] 불필요한 코드는 삭제했어요.

2024-02-13 10:19 UTC, catturtle123 approved these changes

2024-02-13 16:23 UTC, eomgerm requested changes

2024-02-13 16:23 UTC, eomgerm commented on src/main/java/com/avab/avab/controller/FlowController.java
> +    @GetMapping("/recommend")
동사형 보다는 recommended로 명사형이 좀더 restful 할 것 같습니다!

2024-02-14 05:09 UTC, eomgerm approved these changes

2024-02-14 05:10 UTC, merged