♻️  [Refactor]: 플로우 생성에 사용자 지정 레크레이션 추가
TeamAvAb/AvAb-Back pull request #114
Opened 2024-02-13 08:02 UTC by jinuklee777

## 📍 PR 타입 (하나 이상 선택)
- [x] 기능 추가
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트
- [x] 기타 사소한 수정

## ❗️ 관련 이슈 링크
Close #107 

## 📌 개요
- 플로우를 생성할때 기존 레크레이션과 사용자 지정 레크레이션을 모두 받을 수 있게 하였습니다.

## 🔁 변경 사항

## 📸 스크린샷

## 👀 기타 더 이야기해볼 점

## ✅ 체크 리스트
- [x] PR 템플릿에 맞추어 작성했어요.
- [x] 변경 내용에 대한 테스트를 진행했어요.
- [x] 프로그램이 정상적으로 동작해요.
- [x] PR에 적절한 라벨을 선택했어요.
- [x] 불필요한 코드는 삭제했어요.

2024-02-13 10:53 UTC, eomgerm requested changes

2024-02-13 10:53 UTC, eomgerm commented on src/main/java/com/avab/avab/converter/FlowConverter.java
> +            if (spec.getRecreationId() != null) {
이거 이렇게 찾지 말고 service에서 해쉬맵으로 매핑한다음에 전달해줘도 되지 않을까요?

2024-02-14 06:05 UTC, eomgerm approved these changes

2024-02-14 06:07 UTC, catturtle123 approved these changes

2024-02-14 06:22 UTC, merged