:sparkles: [Feat]: flow 수정 구현(일단 모두 삭제한 후 작성으로 구현)
TeamAvAb/AvAb-Back pull request #128
Opened 2024-02-15 13:47 UTC by catturtle123

- flow 수정 (모두 삭제한 후 작성)

## 📍 PR 타입 (하나 이상 선택)
- [x] 기능 추가
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트
- [ ] 기타 사소한 수정

## ❗️ 관련 이슈 링크
Close #77 

## 📌 개요
- flow 수정 기능 구현

## 🔁 변경 사항

- flow 수정

## 📸 스크린샷

## 👀 기타 더 이야기해볼 점

## ✅ 체크 리스트
- [x] PR 템플릿에 맞추어 작성했어요.
- [x] 변경 내용에 대한 테스트를 진행했어요.
- [x] 프로그램이 정상적으로 동작해요.
- [x] PR에 적절한 라벨을 선택했어요.
- [x] 불필요한 코드는 삭제했어요.

2024-02-15 13:54 UTC, eomgerm requested changes
결국 연관관계 전부 삭제하고 하는걸로 하셨군요ㅠ...
리뷰 하나만 확인해주세요

2024-02-15 13:54 UTC, eomgerm commented on src/main/java/com/avab/avab/controller/FlowController.java
> +import org.springframework.web.bind.annotation.*;
이거 억지로 *로 하신건가요?

2024-02-15 13:58 UTC, catturtle123 commented on src/main/java/com/avab/avab/controller/FlowController.java
> +import org.springframework.web.bind.annotation.*;
아니요 그냥 바뀐 것 같습니다..

2024-02-15 13:59 UTC, eomgerm commented on src/main/java/com/avab/avab/controller/FlowController.java
> +import org.springframework.web.bind.annotation.*;
spotless가 자동으로 바꿔줬단 뜻이죠?

2024-02-15 15:09 UTC, catturtle123 commented on src/main/java/com/avab/avab/controller/FlowController.java
> +import org.springframework.web.bind.annotation.*;
그런 것 같습니다..

2024-02-15 15:10 UTC, eomgerm approved these changes

2024-02-16 10:49 UTC, jinuklee777 approved these changes

2024-02-16 11:37 UTC, merged