Feat: 시큐리티 설정
TeamAvAb/AvAb-Back pull request #14
Opened 2024-01-16 16:36 UTC by catturtle123

- security config 설정
- jwt 설정

## 📍 PR 타입 (하나 이상 선택)
- [ ] 기능 추가
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트
- [ ] 기타 사소한 수정

## ❗️ 관련 이슈 링크
Close #13 

## 📌 개요
- 시큐리티 설정

## 🔁 변경 사항
- security config 추가
- jwt 기능 추가

## 📸 스크린샷

## 👀 기타 더 이야기해볼 점
- 현재는 cors를 Default로 놔두었는데 나중에 고쳐야할지
- jwt를 받을려면 관련 controller가 필요할 것 같아서 일단 놔두었습니다.
- 카카오 callback 주소는 아직 전체 권한 부여를 해놓지 않았습니다.
- 아직 redis는 설정하지 않았습니다.

## ✅ 체크 리스트
- [ ] PR 템플릿에 맞추어 작성했어요.
- [ ] 변경 내용에 대한 테스트를 진행했어요.
- [ ] 프로그램이 정상적으로 동작해요.
- [ ] PR에 적절한 라벨을 선택했어요.
- [ ] 불필요한 코드는 삭제했어요.

2024-01-16 17:17 UTC, eomgerm requested changes
고생 많으셨어요! 리뷰들 읽어보시고 수정 및 추가의견 부탁드려요

2024-01-16 17:17 UTC, eomgerm commented on src/main/java/com/avab/avab/apiPayload/code/status/ErrorStatus.java
> +    _USER_NOT_FOUND(HttpStatus.NOT_FOUND, "USER_001", "없는 유저 입니다."),
에러는 굳이 _ 붙이지 않아도 될 것 같습니다! 이건 앞으로도 마찬가지일 것 같아요.

2024-01-16 17:17 UTC, eomgerm commented on src/main/java/com/avab/avab/auth/test/AuthController.java
> +    public ResponseEntity<?> signup(@RequestBody LoginRequest request) {
로그인과 회원가입에 대해서는 테스트 코드인거죠? 코드가 불완전해보여 여쭤봅니다!

2024-01-16 17:17 UTC, eomgerm commented on src/main/java/com/avab/avab/auth/test/AuthController.java
> +    @GetMapping("/test")
이런 테스트 코드도 삭제 부탁드려요!

2024-01-16 17:17 UTC, eomgerm commented on src/main/java/com/avab/avab/config/SecurityConfig.java
> +        http.cors(Customizer.withDefaults());
cors는 추후에 webconfig 추가하면서 하면 됩니다!

2024-01-16 17:17 UTC, eomgerm commented on src/main/java/com/avab/avab/config/SecurityConfig.java
> +        http.csrf(AbstractHttpConfigurer::disable);
저희가 웹 서비스를 제공하다보니 CSRF는 허용해야 할 것 같습니다!

2024-01-16 17:17 UTC, eomgerm commented on src/main/java/com/avab/avab/domain/Recreation.java
> +import java.util.ArrayList;
왜 이런 불필요한 임포트 정리들이 생기는걸까요??? 컨벤션 맞추도록 설정해놔서 괜찮을텐데...

2024-01-16 17:17 UTC, eomgerm commented on src/main/resources/application.yml
> +jwt:
jwt와 관련된 환경 변수도 노션에 추가 부탁합니다!

2024-01-16 18:15 UTC, catturtle123 commented on src/main/java/com/avab/avab/apiPayload/code/status/ErrorStatus.java
> +    _USER_NOT_FOUND(HttpStatus.NOT_FOUND, "USER_001", "없는 유저 입니다."),
넵 알겠습니다!

2024-01-16 18:16 UTC, catturtle123 commented on src/main/java/com/avab/avab/auth/test/AuthController.java
> +    @GetMapping("/test")
넵!

2024-01-16 18:16 UTC, catturtle123 commented on src/main/java/com/avab/avab/config/SecurityConfig.java
> +        http.cors(Customizer.withDefaults());
넵!

2024-01-16 18:18 UTC, catturtle123 commented on src/main/java/com/avab/avab/domain/Recreation.java
> +import java.util.ArrayList;
따로 설정해야하는 부분이 있을까요?

2024-01-16 18:20 UTC, eomgerm commented on src/main/java/com/avab/avab/domain/Recreation.java
> +import java.util.ArrayList;
커밋하기전에 한 번 실행하면 되는데 근데 따로 파일을 안 건드셨는데도 이런 현상이 발생하는 거면 뭔가 문제가 있는 것 같네요... 이번에는 일단 넘어가는데 지속적으로 이런 일이 발생하면 수정할 필요가 있을 것 같아요

2024-01-16 18:21 UTC, catturtle123 commented on src/main/resources/application.yml
> +jwt:
넵! 추가하였습니다!

2024-01-16 18:21 UTC, catturtle123 commented on src/main/java/com/avab/avab/config/SecurityConfig.java
> +        http.csrf(AbstractHttpConfigurer::disable);
넵!

2024-01-16 18:24 UTC, catturtle123 commented on src/main/java/com/avab/avab/auth/test/AuthController.java
> +    public ResponseEntity<?> signup(@RequestBody LoginRequest request) {
제가 깜박하고 sign-up코드를 안 지웠었네요 로그인만 테스트 코드로 남겨 놓았었습니다. 데이터베이스에 직접 user를 추가하고 테스트하는 방식으로 했었는데 회원 가입을 추가할까요?

2024-01-16 18:26 UTC, eomgerm commented on src/main/java/com/avab/avab/auth/test/AuthController.java
> +    public ResponseEntity<?> signup(@RequestBody LoginRequest request) {
아뇨 회원가입은 나중에 카카오 로그인이랑 통합해야 해서 일단 보류입니다! 로그인이랑 회원가입 등등 테스트로 진행한 코드랑 파일들은 우선 삭제 부탁드려요 :)

2024-01-16 19:01 UTC, catturtle123 commented on src/main/java/com/avab/avab/domain/Recreation.java
> +import java.util.ArrayList;
넵!

2024-01-16 19:17 UTC, eomgerm approved these changes

2024-01-16 19:17 UTC, eomgerm commented on src/main/java/com/avab/avab/auth/principal/PrincipalDetailsService.java
>                                          new UsernameNotFoundException(
혹시 이 부분도 AuthException으로 해주실 수 있나용?

2024-01-16 19:19 UTC, eomgerm requested changes

2024-01-16 19:19 UTC, eomgerm commented on src/main/java/com/avab/avab/auth/principal/PrincipalDetailsService.java
> +                                        new UsernameNotFoundException(
혹시 이 부분도 AuthException으로 바꿔주실 수 있나요?

2024-01-16 19:21 UTC, catturtle123 commented on src/main/java/com/avab/avab/auth/principal/PrincipalDetailsService.java
> +                                        new UsernameNotFoundException(
넵! 바로 바꾸겠습니다!

2024-01-16 19:34 UTC, eomgerm approved these changes
밤 늦게까지 고생하셨습니다! 시큐리티 걱정 많이 했는데 제이미님 덕분에 금방 해결했네요! 감사합니다 ㅎㅎ

2024-01-17 04:02 UTC, 88dldl approved these changes
확인했습니다 ! 👍

2024-01-17 05:19 UTC, merged