:sparkles: [Feat]: 마스킹 관련 고도화
TeamAvAb/AvAb-Back pull request #183
Opened 2024-10-08 14:48 UTC by eomgerm

## 📍 PR 타입 (하나 이상 선택)
- [x] 기능 추가
- [x] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트
- [x] 기타 사소한 수정

## ❗️ 관련 이슈 링크
Close #182 

## 📌 개요

## 🔁 변경 사항

## 📸 스크린샷

## 👀 기타 더 이야기해볼 점
변경사항 노션 > 마스킹 관련 정책 확인해주세요.
각자 테스트 하시고 안되는 점 PR 댓글로 달아주세요.

## ✅ 체크 리스트
- [ ] PR 템플릿에 맞추어 작성했어요.
- [ ] 변경 내용에 대한 테스트를 진행했어요.
- [ ] 프로그램이 정상적으로 동작해요.
- [ ] PR에 적절한 라벨을 선택했어요.
- [ ] 불필요한 코드는 삭제했어요.

2024-10-08 14:59 UTC, catturtle123 approved these changes
넵 고생하셨습니다!

2024-10-08 15:50 UTC, eomgerm commented
탈퇴한 회원 마스킹은 잘 동작함

2024-10-10 14:06 UTC, 88dldl commented
[직접삭제]
공통 - soft delete 문제 없음 
레크레이션 - 삭제 후 즐겨찾기한 레크레이션에서 표시됨
플로우 - 관련 스크랩 기록 미삭제 ⇒ DB에서 삭제됨 (deleteAPI 사용)  
레크레이션 리뷰(댓글) - 해당 레크레이션 별점 즉시 반영 ⇒ db에서 지우면 즉시 반영안됨(update안된듯합니다 API 만들고 테스트 해보는건 어떨까요??)

2024-10-10 15:49 UTC, catturtle123 requested changes
### 공통
- 신고한 콘텐츠는 신고자에게 자동 마스킹 ✅
- 신고 누적된 경우 해당 콘텐츠 삭제 처리 → 이후 삭제 정책과 동일하게 흘러감 ✅
- 신고 누적된 사용자 7일간 이용정지 ✅
### 레크레이션
- 신고자의 즐겨찾기 해제 🚫
- 이후 플로우에서 신고한 콘텐츠라고 표시 ✅
### 플로우
- 스크랩 해제 🚫
### 리뷰
- 추천/비추천 해제 🚫
- 별점은 영향 미치지 않음 ✅

각 해제가 안되는 모습

부가적으로 현재 dev DB에 기존 레크레이션이 한 유저에게 몰려있는데 그 사람이 신고를 많이 당해 삭제가 된다면 모든 레크레이션이 사라질 수 있다는 우려가 있음.

2024-10-14 07:36 UTC, eomgerm commented
https://github.com/TeamAvAb/AvAb-Back/pull/183#issuecomment-2405194199

레크레이션 리뷰는 API 만들어서 서비스 로직 구현해야 합니다!

2024-10-14 07:36 UTC, eomgerm commented
https://github.com/TeamAvAb/AvAb-Back/pull/183#pullrequestreview-2360787897

어차피 dev DB는 개발용이라 출시를 위해서는 프로덕션 레벨의 DB 구성해야합니다.

2024-10-20 10:30 UTC, merged