:sparkles: [Feat] 레크레이션 상세설명 API, 레크레이션 존재 검증 어노테이션 구현
TeamAvAb/AvAb-Back pull request #25
Opened 2024-01-17 20:41 UTC by 88dldl

## 📍 PR 타입 (하나 이상 선택)
- [X] 기능 추가
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트
- [ ] 기타 사소한 수정

## ❗️ 관련 이슈 링크
Close #15

## 📌 개요
- 레크레이션 상세설명 API 구현

## 🔁 변경 사항
- RecreationController, RecreationService(Impl), RecreationRepository, RecreationResponseDTO, RecreationConverter에 추가,
SecurityConfig에 상세설명 endpoint추가
- 레크레이션 존재 검증 어노테이션 (ExistRecreations) 구현
 : 3ecbad1acca93d4e64262d84381deb934a6158e4  -> 여기 확인해주시면 됩니다 ! 
 : ConstraintValidator 사용해서 validator 패키지 안에 만들어 뒀습니다. @ Validated 붙여서 사용하시면 될 것 같습니다. 혹시 수정해야할사항이 있다면 알려주세요!!!!

- 원래 커밋이 저렇게 한번에 많이 올라가나요?? 골라서 올려야하는거 제가 다 올린건가요 ,,,,,,,,,,,

## 📸 스크린샷

## 👀 기타 더 이야기해볼 점
- [x] 예외처리(레크레이션 아이디 존재여부 확인 등)를 하나도 하지 않았는데 추가해야 할까요?
- [x] api구성을 **description/{recreationId}** 로 처리해뒀는데 **{recreationId}/description** 가 훨씬 괜찮다고 생각합니다! 근데  SecurityConfig에 endpoint를   **/api/recreations/*/description** 이렇게 적어서 테스트해봤더니 에러가 떠서 일단은 **description/{recreationId}** api설정해뒀습니다!  -> **{recreationId}/description** 이렇게 설정할 경우 endpoint를 어떻게 적어야할까요,,, 

## ✅ 체크 리스트
- [x] PR 템플릿에 맞추어 작성했어요.
- [x] 변경 내용에 대한 테스트를 진행했어요.
- [x] 프로그램이 정상적으로 동작해요.
- [x] PR에 적절한 라벨을 선택했어요.
- [x] 불필요한 코드는 삭제했어요.

2024-01-18 05:04 UTC, catturtle123 commented on src/main/java/com/avab/avab/config/SecurityConfig.java
> +        "/api/recreations/description/*"
방금 해보니까 /api/recreations/{recreationId}/description 이런 식으로 해주면 되는 거 같아요!

2024-01-18 05:43 UTC, eomgerm requested changes

2024-01-18 05:43 UTC, eomgerm commented on src/main/java/com/avab/avab/controller/RecreationController.java
> +    @GetMapping("/{recreationId}/description")
/description은 굳이 없어도 될 것 같아요

2024-01-18 06:19 UTC, eomgerm requested changes

2024-01-18 06:19 UTC, eomgerm commented on src/main/java/com/avab/avab/service/impl/RecreationServiceImpl.java
> +        return RecreationConverter.toDescriptionDTO(recreation);
Service는 엔티티만 응답합니다! DTO로 변환하는 건 컨트롤러에서 해주세요

2024-01-18 06:55 UTC, 88dldl commented on src/main/java/com/avab/avab/service/impl/RecreationServiceImpl.java
> +        return RecreationConverter.toDescriptionDTO(recreation);
수정확인부탁드립니다~!

2024-01-18 10:06 UTC, eomgerm requested changes

2024-01-18 10:06 UTC, eomgerm commented on src/main/java/com/avab/avab/dto/recreation/RecreationResponseDTO.java
> +        List<String> wayList;
방법에 이미지 추가해야 합니다!

2024-01-18 10:06 UTC, eomgerm commented on src/main/java/com/avab/avab/dto/recreation/RecreationResponseDTO.java
> +    public static class DescriptionDTO {
혹시 모르니 레크레이션 아이디 필드도 추가해주세요

2024-01-18 10:26 UTC, 88dldl commented on src/main/java/com/avab/avab/dto/recreation/RecreationResponseDTO.java
> +    public static class DescriptionDTO {
최최최종 확인부탁드립니다!

2024-01-18 11:05 UTC, eomgerm requested changes

2024-01-18 11:05 UTC, eomgerm commented on src/main/java/com/avab/avab/converter/RecreationConverter.java
> +                .wayImgList(wayImgList)
이렇게 하면 프런트에서 매핑하기가 어려워집니다ㅠㅠ
방법 DTO를 하나더 만들어서
그걸 또 리스트 형태로 담아줘야 해요
```
...
wayList: [
  {
      imageUrl: ~~~
      contents: ~~~~
   },
   ...
]
...
```
이런 식으로요!

2024-01-18 11:06 UTC, 88dldl commented on src/main/java/com/avab/avab/converter/RecreationConverter.java
> +                .wayImgList(wayImgList)
그렇군요 ㅜㅜ 수정해오겠습니다

2024-01-18 11:40 UTC, eomgerm requested changes

2024-01-18 11:40 UTC, eomgerm commented on src/main/java/com/avab/avab/dto/recreation/RecreationResponseDTO.java
> +        String wayList;
수기님 이름...ㅜ waylist가 아니고 contents여야죠...

2024-01-18 11:40 UTC, eomgerm commented on src/main/java/com/avab/avab/dto/recreation/RecreationResponseDTO.java
> +        String wayImgList;
이것도 마찬가지로 imageUrl!

2024-01-18 11:41 UTC, 88dldl commented on src/main/java/com/avab/avab/dto/recreation/RecreationResponseDTO.java
> +        String wayImgList;
참.... 하다보니 뇌가 빠졌나보네요 수정해오겠습니다 !!!!!

2024-01-18 18:36 UTC, eomgerm requested changes
고생하셨습니다! 파일 위치랑 이름만 바꿔주세요! 그외에는 LGTM입니다!!!!!

2024-01-18 18:36 UTC, eomgerm commented on src/main/java/com/avab/avab/security/handler/annotation/ExistRecreations.java
시큐리티 패키지에 있을 필요 없이 그냥 validation으로 새 폴더 파서 하위 폴더로 annotation이랑 validator 폴더 만들어서 어노테이션이랑 validator 클래스 각각 넣어주세요! 그리고 어노테이션 이름도 복수형 말고 단수형으로 해서 ExistRecreation으로 해주시면 될 것 같아요!

2024-01-18 18:45 UTC, 88dldl commented on src/main/java/com/avab/avab/security/handler/annotation/ExistRecreations.java
수정했습니다 !

2024-01-18 18:52 UTC, eomgerm approved these changes
진짜 고생하셨습니다!!!!

2024-01-19 05:53 UTC, jinuklee777 requested changes

2024-01-19 05:53 UTC, jinuklee777 commented on src/main/java/com/avab/avab/security/handler/resolver/AuthUserArgumentResolver.java
> +        System.out.println("hihi");
이거 System.out.println은 없애고 올려야 할거 같습니다!

2024-01-19 06:11 UTC, 88dldl commented on src/main/java/com/avab/avab/security/handler/resolver/AuthUserArgumentResolver.java
> +        System.out.println("hihi");
엇 보노님이 수정하셨다고 했는데 안되어있었군요

2024-01-19 06:15 UTC, 88dldl commented on src/main/java/com/avab/avab/security/handler/resolver/AuthUserArgumentResolver.java
> +        System.out.println("hihi");
다시한번만 확인해주세요~

2024-01-19 06:16 UTC, jinuklee777 approved these changes
수고많으셨습니당~~

2024-01-19 06:17 UTC, merged