:sparkles: [Feat]: 카카오 로그인 구현
TeamAvAb/AvAb-Back pull request #31
Opened 2024-01-20 07:57 UTC by catturtle123

- 카카오 로그인
- 카카오 회원가입
- refresh token 구현(redis 사용)

## 📍 PR 타입 (하나 이상 선택)
- [x] 기능 추가
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트
- [ ] 기타 사소한 수정

## ❗️ 관련 이슈 링크
Close #20 

## 📌 개요
- 카카오 로그인 구현

## 🔁 변경 사항
- redis 패키지 밑에 로그인 관련 controller, service, repository 추가
- security config /auth 주소 추가
- 카카오 로그인 및 회원가입 구 

## 📸 스크린샷

## 👀 기타 더 이야기해볼 점
- 현재 nickname 또한 kakao 서버에서 받아서 저장하도록 설정되어있습니다. 바꾸어야 할까요?

## ✅ 체크 리스트
- [x] PR 템플릿에 맞추어 작성했어요.
- [x] 변경 내용에 대한 테스트를 진행했어요.
- [x] 프로그램이 정상적으로 동작해요.
- [x] PR에 적절한 라벨을 선택했어요.
- [x] 불필요한 코드는 삭제했어요.

2024-01-20 16:12 UTC, eomgerm requested changes
여쭤보고 싶은 거랑 하고 싶은 얘기가 많아서요! 저희 한 번 따로 이야기를 나눌 필요가 있을 것 같습니다. 자세한 얘기는 디코 확인해주세요!

2024-01-21 16:30 UTC, eomgerm commented on src/main/java/com/avab/avab/controller/AuthController.java
> +    @GetMapping("/auth/login/kakao") // redirect uri를 여기에 적어야 합니다. (변수 안되서 그냥 상수로 적어 놓았습니다.)
주석 무슨 뜻인가요??

2024-01-21 17:27 UTC, catturtle123 commented on src/main/java/com/avab/avab/controller/AuthController.java
> +    @GetMapping("/auth/login/kakao") // redirect uri를 여기에 적어야 합니다. (변수 안되서 그냥 상수로 적어 놓았습니다.)
환경변수로 redirectUri를 적어놓았는데 @Value로 GetMapping에 넣는 것이 불가능 해서 일단 주석으로 적어놓았습니다!

2024-01-21 17:34 UTC, eomgerm commented on src/main/java/com/avab/avab/controller/AuthController.java
> +    @GetMapping("/auth/login/kakao") // redirect uri를 여기에 적어야 합니다. (변수 안되서 그냥 상수로 적어 놓았습니다.)
왜 redirectUri를 주입 받아야 하는건가요?!

2024-01-21 17:38 UTC, catturtle123 commented on src/main/java/com/avab/avab/controller/AuthController.java
> +    @GetMapping("/auth/login/kakao") // redirect uri를 여기에 적어야 합니다. (변수 안되서 그냥 상수로 적어 놓았습니다.)
다른 곳에서도 써서 한번에 주입해주면 통일성이 생긴다고 생각해서 넣었습니다! 다른 곳에서는 쓰는 곳이 한 곳밖에 없어서 않아서 다른 곳도 그냥 문자열로 넣어도 되긴합니다!

2024-01-21 17:40 UTC, eomgerm commented on src/main/java/com/avab/avab/controller/AuthController.java
> +    @GetMapping("/auth/login/kakao") // redirect uri를 여기에 적어야 합니다. (변수 안되서 그냥 상수로 적어 놓았습니다.)
아아 이해했어요! 근데 제가 생각했을 때 `clientId`는 민감 정보이지만 `redirectionUri`는 아닌 것 같아서요!
redirect uri는 굳이 환경변수로 받을 필요는 없을 것 같습니다!
아니면 제가 잘 못 생각하고 있는걸까요?

2024-01-21 20:12 UTC, catturtle123 commented on src/main/java/com/avab/avab/controller/AuthController.java
> +    @GetMapping("/auth/login/kakao") // redirect uri를 여기에 적어야 합니다. (변수 안되서 그냥 상수로 적어 놓았습니다.)
카카오에서 오는 건 다 환경변수로 해야겠다는 생각이 있어서 그랬던 것 같습니다! 바꿔서 다시 커밋하겠습니다!

2024-01-21 20:25 UTC, eomgerm commented on src/main/java/com/avab/avab/security/provider/KakaoAuthProvider.java
> +        params.add("redirect_uri", "http://localhost:8080/auth/login/kakao");
근데 이렇게 하면 배포환경에서 정상적으로 작동하나요??
배포 환경에서는 배포 환경에 맞는 도메인을 써야할 것 같은데요!

2024-01-22 03:33 UTC, catturtle123 commented on src/main/java/com/avab/avab/security/provider/KakaoAuthProvider.java
> +        params.add("redirect_uri", "http://localhost:8080/auth/login/kakao");
아직 도메인이 나오지 않아서요! 어떻게 해놓는게 좋을까요?

2024-01-22 05:39 UTC, eomgerm commented on src/main/java/com/avab/avab/security/provider/KakaoAuthProvider.java
> +        params.add("redirect_uri", "http://localhost:8080/auth/login/kakao");
아... 그러면 로컬 환경일 때랑 배포 환경일 때랑 따로 구분이 필요하겠네요 민감 정보는 아니더라도 환경에 따라 다른 값이 필요하니 이전 처럼 환경변수로 받는게 맞는 것 같습니다....

2024-01-22 05:46 UTC, catturtle123 commented on src/main/java/com/avab/avab/security/provider/KakaoAuthProvider.java
> +        params.add("redirect_uri", "http://localhost:8080/auth/login/kakao");
넵 알겠습니다! Getmapping 쪽에 주석도 다시 추가할까요?

2024-01-22 05:46 UTC, eomgerm commented on src/main/java/com/avab/avab/security/provider/KakaoAuthProvider.java
> +        params.add("redirect_uri", "http://localhost:8080/auth/login/kakao");
그건 필요없을 듯합니다! 어차피 환경변수에는 전체 주소가 들어가야하니까요

2024-01-22 05:48 UTC, catturtle123 commented on src/main/java/com/avab/avab/security/provider/KakaoAuthProvider.java
> +        params.add("redirect_uri", "http://localhost:8080/auth/login/kakao");
넵 알겠습니다!

2024-01-23 17:05 UTC, eomgerm requested changes

2024-01-23 17:05 UTC, eomgerm commented on src/main/java/com/avab/avab/controller/AuthController.java
> +        authServiceImpl.logout(user.getId());
이거 왜 authserviceimpl을 그대로 가져온건가요...? 그냥 인터페이스를 가져와도 됩니다!!

2024-01-23 17:05 UTC, eomgerm commented on src/main/resources/application.yml
> +    redirect-uri: ${REDIRECT_URI}
해당 환경변수도 노션에 남겨주세요!

2024-01-23 17:15 UTC, catturtle123 commented on src/main/resources/application.yml
> +    redirect-uri: ${REDIRECT_URI}
넵!

2024-01-23 17:22 UTC, catturtle123 commented on src/main/java/com/avab/avab/controller/AuthController.java
> +        authServiceImpl.logout(user.getId());
넵!!

2024-01-23 17:36 UTC, eomgerm approved these changes
굿 고생하셨습니다! 충돌 해결하고 머지해주세요!

2024-01-24 07:16 UTC, 88dldl approved these changes
수고하셨습니다 👍

2024-01-26 08:58 UTC, eomgerm requested changes

2024-01-26 08:58 UTC, eomgerm commented on src/main/java/com/avab/avab/controller/AuthController.java
이거 엔드포인트 /api/auth로 바꿔주실래요?

2024-01-26 11:26 UTC, catturtle123 commented on src/main/java/com/avab/avab/controller/AuthController.java
넵!  알겠습니다!

2024-01-26 14:59 UTC, eomgerm approved these changes

2024-01-26 15:13 UTC, merged