:sparkles: [Feat]: 회원 정보 수정 API 구현
TeamAvAb/AvAb-Back pull request #49
Opened 2024-01-24 14:26 UTC by jinuklee777

## 📍 PR 타입 (하나 이상 선택)
- [x] 기능 추가
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트
- [ ] 기타 사소한 수정

## ❗️ 관련 이슈 링크
Close #46 

## 📌 개요
- 회원의 닉네임을 수정하는 API 입니다.

## 🔁 변경 사항

## 📸 스크린샷

## 👀 기타 더 이야기해볼 점

## ✅ 체크 리스트
- [x] PR 템플릿에 맞추어 작성했어요.
- [x] 변경 내용에 대한 테스트를 진행했어요.
- [x] 프로그램이 정상적으로 동작해요.
- [x] PR에 적절한 라벨을 선택했어요.
- [x] 불필요한 코드는 삭제했어요.

2024-01-25 06:21 UTC, eomgerm requested changes

2024-01-25 06:21 UTC, eomgerm commented on src/main/java/com/avab/avab/dto/reqeust/UserRequestDTO.java
> +        private String name;
이거 비어있으면 안되니까 NotBlank 어노테이션 붙여주세요

2024-01-25 06:21 UTC, eomgerm commented on src/main/java/com/avab/avab/controller/UserController.java
> +            @RequestBody UpdateUserNameDTO updateUserNameDTO, @AuthUser User user) {
body 검증해야 하니까 Valid 어노테이션 붙여주세요

2024-01-25 06:21 UTC, eomgerm commented on src/main/java/com/avab/avab/converter/UserConverter.java
> +    public static UserResponseDTO.UserResponse convertUserToUserResponse(User user) {
저희 네임 컨벤션에 맞춰서 toUserResponse로 바꿔주세요!

2024-01-25 06:21 UTC, eomgerm commented on src/main/java/com/avab/avab/service/impl/UserServiceImpl.java
> +        User existUser =
어차피 AuthUser에서 사용자 존재 여부 확인하기 때문에 서비스에서 한 번 더 검증할 필요 없습니다~!

2024-01-26 01:46 UTC, 88dldl approved these changes
확인했습니다 !

2024-01-26 04:30 UTC, eomgerm approved these changes
사실 확장성을 생각한다면 '내 정보' 수정이니까 Name을 제외한 다른 필드도 받아야 할 수 있기 때문에, UpdateUserName이 아니라 UpdateMyInfo 등으로 바꿔서 전체적인 상황을 커버하는 게 올바를 수도 있어용! 일단 지금은 이름 수정만 요구사항에 있으니 승인합니다~ 고생하셨어요~~~

2024-01-26 07:48 UTC, catturtle123 approved these changes
확인하였습니다!

2024-01-31 04:09 UTC, merged