✨ [Feat] 연관레크레이션 목록 API구현
TeamAvAb/AvAb-Back pull request #53
Opened 2024-01-25 22:59 UTC by 88dldl

## 📍 PR 타입 (하나 이상 선택)
- [X] 기능 추가
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트
- [X] 기타 사소한 수정

## ❗️ 관련 이슈 링크
Close #38

## 📌 개요
- 연관 레크레이션 목록 API구현했습니다.

## 🔁 변경 사항
- Elastic search로 하다가는 시간이 오래 걸릴 것 같아 Querydsl 사용했습니다
- 이전에 구현한 레크레이션 상세설명 부분에 예외처리 추가했습니다.

## 📸 스크린샷

## 👀 기타 더 이야기해볼 점

## ✅ 체크 리스트
- [x] PR 템플릿에 맞추어 작성했어요.
- [x] 변경 내용에 대한 테스트를 진행했어요.
- [x] 프로그램이 정상적으로 동작해요.
- [x] PR에 적절한 라벨을 선택했어요.
- [x] 불필요한 코드는 삭제했어요.

2024-01-26 04:23 UTC, eomgerm requested changes

2024-01-26 04:23 UTC, eomgerm commented on src/main/java/com/avab/avab/converter/RecreationConverter.java
> +                .pageUrl("/api/recreations/" + recreation.getId())
상세 API url을 넘겨주지 말고 그냥 id를 넘겨준다음에 프런트에서 id로 상세 API를 호출하는 게 더 나을 것 같아요

2024-01-26 04:23 UTC, eomgerm commented on src/main/java/com/avab/avab/dto/response/RecreationResponseDTO.java
> +    public static class RelatedRecreationDTO {
제가 만든 `RecreationPreviewDTO` 재사용 해주세요! 어차피 내용 똑같아요

2024-01-26 04:23 UTC, eomgerm commented on src/main/java/com/avab/avab/dto/response/RecreationResponseDTO.java
> +        List<RelatedRecreationDTO> relatedRecreationList;
이런 방법도 좋지만 굳이 다른 필드가 없는 경우에는 DTO로 따로 뺄 필요없이 컨트롤러에서 List로 넘겨주세요

2024-01-26 04:23 UTC, eomgerm commented on src/main/java/com/avab/avab/repository/RecreationCustomRepository.java
> +    List<Recreation> relatedRecreations(
함수명은 동사가 들어가는 편이 좋아서 findRelatedRecreations로 해주세요!

2024-01-26 04:23 UTC, eomgerm commented on src/main/java/com/avab/avab/service/RecreationService.java
> +    List<Recreation> relatedRecreations(Long recreationId);
여기도 마찬가지로 동사형으로 이름 지어주세요!

2024-01-26 04:23 UTC, eomgerm commented on src/main/java/com/avab/avab/controller/RecreationController.java
> +        List<Boolean> favorites = recreationService.getFavoriteList(relatedRecreation, user);
이렇게 따로 조회하면 순서가 동일하다는 보장이 없기 때문에 정확하게 매치가 되지 않을 수도 있어요...

2024-01-26 05:48 UTC, 88dldl commented on src/main/java/com/avab/avab/dto/response/RecreationResponseDTO.java
> +    public static class RelatedRecreationDTO {
그렇게 되면 RecreationPreviewDTO 에 purpose가 없네요ㅜ

2024-01-26 05:50 UTC, eomgerm commented on src/main/java/com/avab/avab/dto/response/RecreationResponseDTO.java
> +    public static class RelatedRecreationDTO {
디자인에는 목적 관련 UI가 없어서 필요 없을 것 같습니다!

2024-01-26 05:51 UTC, 88dldl commented on src/main/java/com/avab/avab/dto/response/RecreationResponseDTO.java
> +    public static class RelatedRecreationDTO {
해시태그가 목적이라 그냥 해시태그였군요!!! 전 이제껏 목적인줄,,, 알았네요 확인했습니다 !

2024-01-26 15:04 UTC, eomgerm requested changes
이거 제가 말씀드린 거랑 좀 다르게 하셨는데... 혹시 그냥 제가 수정해서 커밋해도 될까...요...?

2024-01-26 15:07 UTC, 88dldl commented
> 이거 제가 말씀드린 거랑 좀 다르게 하셨는데... 혹시 그냥 제가 수정해서 커밋해도 될까...요...?

아 넵!! 그래주시면 감사하겠습니다 !

2024-01-31 04:37 UTC, eomgerm approved these changes

2024-01-31 04:42 UTC, jinuklee777 approved these changes

2024-01-31 04:42 UTC, merged