✨ [Feat] 연관 플로우 목록 API 구현
TeamAvAb/AvAb-Back pull request #74
Opened 2024-02-01 03:20 UTC by 88dldl

## 📍 PR 타입 (하나 이상 선택)
- [X] 기능 추가
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트
- [X] 기타 사소한 수정

## ❗️ 관련 이슈 링크
Close #68

## 📌 개요
- 연관 플로우 목록 API 구현했습니다 

## 🔁 변경 사항
1. 연관 플로우 목록 구현 -> 연관된 플로우 목록이 많을 경우 랜덤으로 2개 리턴하도록 했습니다.
2. 연관 레크레이션 api 이름 수정했습니다 (related-> relatedRecreation)

## 📸 스크린샷

## 👀 기타 더 이야기해볼 점

## ✅ 체크 리스트
- [X] PR 템플릿에 맞추어 작성했어요.
- [X] 변경 내용에 대한 테스트를 진행했어요.
- [X] 프로그램이 정상적으로 동작해요.
- [X] PR에 적절한 라벨을 선택했어요.
- [X] 불필요한 코드는 삭제했어요.

2024-02-01 13:12 UTC, eomgerm requested changes

2024-02-01 13:12 UTC, eomgerm commented on src/main/java/com/avab/avab/controller/RecreationController.java
> +    @GetMapping("/{recreationId}/relatedRecreation")
related/recreations, related/flows 이런 엔드포인트는 어떠신가요?

2024-02-02 02:24 UTC, 88dldl commented on src/main/java/com/avab/avab/controller/RecreationController.java
> +    @GetMapping("/{recreationId}/relatedRecreation")
음 그것도 좋은것같아요 ! 수정해서 올리겠습니다 !

2024-02-02 12:14 UTC, eomgerm approved these changes

2024-02-02 12:44 UTC, catturtle123 approved these changes

2024-02-03 01:35 UTC, merged