✨  [Feat]: 플로우 생성 API
TeamAvAb/AvAb-Back pull request #75
Opened 2024-02-01 12:41 UTC by jinuklee777

## 📍 PR 타입 (하나 이상 선택)
- [x] 기능 추가
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트
- [ ] 기타 사소한 수정

## ❗️ 관련 이슈 링크
Close #66 

## 📌 개요
- 플로우를 생성하는 API 입니다.

## 🔁 변경 사항
- FlowRecreation 테이블에 Integer seq를 추가했습니다.

## 📸 스크린샷

## 👀 기타 더 이야기해볼 점

## ✅ 체크 리스트
- [x] PR 템플릿에 맞추어 작성했어요.
- [x] 변경 내용에 대한 테스트를 진행했어요.
- [x] 프로그램이 정상적으로 동작해요.
- [x] PR에 적절한 라벨을 선택했어요.
- [x] 불필요한 코드는 삭제했어요.

2024-02-01 13:09 UTC, eomgerm requested changes

2024-02-01 13:09 UTC, eomgerm commented on src/main/java/com/avab/avab/controller/FlowController.java
> +    @PostMapping("/create")
ResponseStatus 어노테이션 추가부탁합니다!

2024-02-01 13:09 UTC, eomgerm commented on src/main/java/com/avab/avab/service/impl/FlowServiceImpl.java
> +@Transactional
얘는 readonly true로 냅두시고 메소드 위에다가 Transactional 붙이면 그 메소드만 쿼리 반영 돼요!

2024-02-01 13:09 UTC, eomgerm commented on src/main/java/com/avab/avab/repository/RecreationKeyWordRepository.java
> +public interface RecreationKeyWordRepository extends JpaRepository<RecreationKeyword, Long> {
RecreationKeyword로 바꿔주세요!

2024-02-01 13:09 UTC, eomgerm commented on src/main/java/com/avab/avab/service/impl/FlowServiceImpl.java
> +        FlowConverter.addFlowRecreation(
이런 add 로직들을 그냥 toFlow 메서드로 넣어주실 수 있나요?

2024-02-02 12:16 UTC, eomgerm approved these changes
한 번에 리팩토링 최곱니다!

2024-02-02 12:33 UTC, catturtle123 approved these changes

2024-02-03 15:12 UTC, merged