:sparkles: [FEAT]: 레크레이션 추천 기능
TeamAvAb/AvAb-Back pull request #76
Opened 2024-02-02 12:15 UTC by catturtle123

## 📍 PR 타입 (하나 이상 선택)
- [ ] 기능 추가
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트
- [ ] 기타 사소한 수정

## ❗️ 관련 이슈 링크
Close #58 

## 📌 개요
- 레크레이션 추천 기능 추가

## 🔁 변경 사항

## 📸 스크린샷

## 👀 기타 더 이야기해볼 점

## ✅ 체크 리스트
- [ ] PR 템플릿에 맞추어 작성했어요.
- [ ] 변경 내용에 대한 테스트를 진행했어요.
- [ ] 프로그램이 정상적으로 동작해요.
- [ ] PR에 적절한 라벨을 선택했어요.
- [ ] 불필요한 코드는 삭제했어요.

2024-02-02 12:18 UTC, eomgerm requested changes

2024-02-02 12:18 UTC, eomgerm commented on src/main/java/com/avab/avab/security/SecurityConfig.java
> +            "/api/recreations/recommend"
이 부분 탭? 있는데 지워주세용!

2024-02-05 09:57 UTC, eomgerm approved these changes
LGTM 👍

2024-02-06 10:18 UTC, 88dldl approved these changes
수고하셨습니다 👍

2024-02-06 17:19 UTC, merged