✨  [Feat]: 플로우 삭제 API 구현
TeamAvAb/AvAb-Back pull request #91
Opened 2024-02-07 11:49 UTC by jinuklee777

## 📍 PR 타입 (하나 이상 선택)
- [x] 기능 추가
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트
- [ ] 기타 사소한 수정

## ❗️ 관련 이슈 링크
Close #84 

## 📌 개요
- 플로우 삭제 API입니다.

## 🔁 변경 사항

## 📸 스크린샷

## 👀 기타 더 이야기해볼 점

## ✅ 체크 리스트
- [x] PR 템플릿에 맞추어 작성했어요.
- [x] 변경 내용에 대한 테스트를 진행했어요.
- [x] 프로그램이 정상적으로 동작해요.
- [x] PR에 적절한 라벨을 선택했어요.
- [x] 불필요한 코드는 삭제했어요.

2024-02-07 12:15 UTC, eomgerm requested changes

2024-02-07 12:15 UTC, eomgerm commented on src/main/java/com/avab/avab/controller/FlowController.java
> +    public BaseResponse<DeletedFlowDTO> deleteFlow(@AuthUser User user, @PathVariable Long flowId) {
ExistsFlow 어노테이션으로 flowId 검증해주세요!

2024-02-07 12:15 UTC, eomgerm commented on src/main/java/com/avab/avab/dto/response/FlowResponseDTO.java
> +        AuthorDTO author;
Author는 왜 넣으신건가요!?

2024-02-07 12:15 UTC, eomgerm commented on src/main/java/com/avab/avab/service/impl/FlowServiceImpl.java
> +        Flow flow = flowRepository.findById(flowId).orElseThrow();
혹시 모르니까 FlowException(ErrorStatus.FLOW_NOT_FOUND) 던져주세요!

2024-02-07 12:22 UTC, jinuklee777 commented on src/main/java/com/avab/avab/dto/response/FlowResponseDTO.java
> +        AuthorDTO author;
굳이 필요 없을까요??

2024-02-07 12:38 UTC, eomgerm commented on src/main/java/com/avab/avab/dto/response/FlowResponseDTO.java
> +        AuthorDTO author;
굳이 있을 필요가 있나 싶어서요! 없는 게 나아보입니다~

2024-02-07 14:24 UTC, eomgerm approved these changes

2024-02-07 16:24 UTC, catturtle123 commented on src/main/java/com/avab/avab/controller/FlowController.java
> +    @Parameter(name = "user", hidden = true)
user parameter 막는 거 잘 작동되시나요? 방금 알았는데 필드 안쪽에 안 있으면 작동이 잘 안되더라구요!

2024-02-08 10:52 UTC, jinuklee777 commented on src/main/java/com/avab/avab/controller/FlowController.java
> +    @Parameter(name = "user", hidden = true)
지금까지 다 이렇게 했었는데 문제가 있나요?? 작동은 잘 했습니당!!

2024-02-08 10:56 UTC, catturtle123 commented on src/main/java/com/avab/avab/controller/FlowController.java
> +    @Parameter(name = "user", hidden = true)
제 로컬에서만 문제가 있었나봐요.. 죄송합니다

2024-02-08 10:56 UTC, catturtle123 approved these changes

2024-02-08 10:57 UTC, catturtle123 commented on src/main/java/com/avab/avab/controller/FlowController.java
> +    @Parameter(name = "user", hidden = true)
avab swagger로 들어가니 문제가 없네요...

2024-02-12 08:01 UTC, merged